apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: interns-webapp-config
  namespace: ladesa-ro-development
spec:
  hostAPI: https://infisical.ladesa.com.br/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
      secretsScope:
        projectSlug: "interns-webapp"
        envSlug: dev
        secretsPath: /
        recursive: true
  managedSecretReference:
    secretName: interns-webapp-secrets
    secretNamespace: ladesa-ro-development
    secretType: Opaque
    creationPolicy: Owner
